const ShopActionsTypes = {
    FETCH_COLLECTIONS_START: "FETCH_COLLECTINS_START",
    FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTINS_SUCCESS",
    FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTINS_FAILURE",
    // UPDATE_COLLECTIONS: "UPDATE_COLLECTIONS"
}

export default ShopActionsTypes